/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ElButton: typeof import('element-plus/es')['ElButton']
    ElConfigProvider: typeof import('element-plus/es')['ElConfigProvider']
    ElContainer: typeof import('element-plus/es')['ElContainer']
    ElFooter: typeof import('element-plus/es')['ElFooter']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElHeader: typeof import('element-plus/es')['ElHeader']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElLink: typeof import('element-plus/es')['ElLink']
    ElMain: typeof import('element-plus/es')['ElMain']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElScrollbar: typeof import('element-plus/es')['ElScrollbar']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElSpace: typeof import('element-plus/es')['ElSpace']
    ElSwitch: typeof import('element-plus/es')['ElSwitch']
    ElTabPane: typeof import('element-plus/es')['ElTabPane']
    ElTabs: typeof import('element-plus/es')['ElTabs']
    ElTooltip: typeof import('element-plus/es')['ElTooltip']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    WmIcon: typeof import('./src/components/wm/icon/index.vue')['default']
    WmLogo: typeof import('./src/components/wm/logo/index.vue')['default']
    WmUserInfo: typeof import('./src/components/wm/user-info/index.vue')['default']
    WmVocInfo: typeof import('./src/components/wm/voc/info/index.vue')['default']
    WmVocInfoPropForm: typeof import('./src/components/wm/voc/info/prop-form.vue')['default']
    WmVocInput: typeof import('./src/components/wm/voc/input/index.vue')['default']
    WmVocInputPropForm: typeof import('./src/components/wm/voc/input/prop-form.vue')['default']
    WmVocParagraph: typeof import('./src/components/wm/voc/paragraph/index.vue')['default']
    WmVocParagraphPropForm: typeof import('./src/components/wm/voc/paragraph/prop-form.vue')['default']
    WmVocTextarea: typeof import('./src/components/wm/voc/textarea/index.vue')['default']
    WmVocTextareaPropForm: typeof import('./src/components/wm/voc/textarea/prop-form.vue')['default']
    WmVocTitle: typeof import('./src/components/wm/voc/title/index.vue')['default']
    WmVocTitlePropForm: typeof import('./src/components/wm/voc/title/prop-form.vue')['default']
  }
  export interface GlobalDirectives {
    vLoading: typeof import('element-plus/es')['ElLoadingDirective']
  }
}
