/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/[...404]': RouteRecordInfo<'/[...404]', '/:404(.*)', { 404: ParamValue<true> }, { 404: ParamValue<false> }>,
    '/detail': RouteRecordInfo<'/detail', '/detail', Record<never, never>, Record<never, never>, '/detail/edit' | '/detail/edit/[:id]' | '/detail/edit/components/component-lib' | '/detail/edit/components/component-prop' | '/detail/edit/components/editor-header' | '/detail/edit/components/left-panel' | '/detail/edit/components/right-panel' | '/detail/stat' | '/detail/stat/[:id]'>,
    '/detail/edit': RouteRecordInfo<'/detail/edit', '/detail/edit', Record<never, never>, Record<never, never>, '/detail/edit/[:id]' | '/detail/edit/components/component-lib' | '/detail/edit/components/component-prop' | '/detail/edit/components/editor-header' | '/detail/edit/components/left-panel' | '/detail/edit/components/right-panel'>,
    '/detail/edit/[:id]': RouteRecordInfo<'/detail/edit/[:id]', '/detail/edit/::id', { :id: ParamValue<true> }, { :id: ParamValue<false> }>,
    '/detail/edit/components/component-lib': RouteRecordInfo<'/detail/edit/components/component-lib', '/detail/edit/components/component-lib', Record<never, never>, Record<never, never>>,
    '/detail/edit/components/component-prop': RouteRecordInfo<'/detail/edit/components/component-prop', '/detail/edit/components/component-prop', Record<never, never>, Record<never, never>>,
    '/detail/edit/components/editor-header': RouteRecordInfo<'/detail/edit/components/editor-header', '/detail/edit/components/editor-header', Record<never, never>, Record<never, never>>,
    '/detail/edit/components/left-panel': RouteRecordInfo<'/detail/edit/components/left-panel', '/detail/edit/components/left-panel', Record<never, never>, Record<never, never>>,
    '/detail/edit/components/right-panel': RouteRecordInfo<'/detail/edit/components/right-panel', '/detail/edit/components/right-panel', Record<never, never>, Record<never, never>>,
    '/detail/stat': RouteRecordInfo<'/detail/stat', '/detail/stat', Record<never, never>, Record<never, never>, '/detail/stat/[:id]'>,
    '/detail/stat/[:id]': RouteRecordInfo<'/detail/stat/[:id]', '/detail/stat/::id', { :id: ParamValue<true> }, { :id: ParamValue<false> }>,
    '/login': RouteRecordInfo<'/login', '/login', Record<never, never>, Record<never, never>>,
    '/manage': RouteRecordInfo<'/manage', '/manage', Record<never, never>, Record<never, never>, '/manage/list' | '/manage/star' | '/manage/trash'>,
    '/manage/list': RouteRecordInfo<'/manage/list', '/manage/list', Record<never, never>, Record<never, never>>,
    '/manage/star': RouteRecordInfo<'/manage/star', '/manage/star', Record<never, never>, Record<never, never>>,
    '/manage/trash': RouteRecordInfo<'/manage/trash', '/manage/trash', Record<never, never>, Record<never, never>>,
    '/register': RouteRecordInfo<'/register', '/register', Record<never, never>, Record<never, never>>,
  }

  /**
   * Route file to route info map by unplugin-vue-router.
   * Used by the volar plugin to automatically type useRoute()
   *
   * Each key is a file path relative to the project root with 2 properties:
   * - routes: union of route names of the possible routes when in this page (passed to useRoute<...>())
   * - views: names of nested views (can be passed to <RouterView name="...">)
   *
   * @internal
   */
  export interface _RouteFileInfoMap {
    'src/pages/index.vue': {
      routes: '/'
      views: never
    }
    'src/pages/[...404].vue': {
      routes: '/[...404]'
      views: never
    }
    'src/pages/detail.vue': {
      routes: '/detail' | '/detail/edit/[:id]' | '/detail/stat/[:id]' | '/detail/edit/components/component-lib' | '/detail/edit/components/component-prop' | '/detail/edit/components' | '/detail/edit' | '/detail/edit/components/editor-header' | '/detail/edit/components/left-panel' | '/detail/edit/components/right-panel' | '/detail/stat'
      views: 'default'
    }
    'src/pages/detail/edit.vue': {
      routes: '/detail/edit' | '/detail/edit/[:id]' | '/detail/edit/components/component-lib' | '/detail/edit/components/component-prop' | '/detail/edit/components' | '/detail/edit/components/editor-header' | '/detail/edit/components/left-panel' | '/detail/edit/components/right-panel'
      views: 'default'
    }
    'src/pages/detail/edit/[:id].vue': {
      routes: '/detail/edit/[:id]'
      views: never
    }
    'src/pages/detail/edit/components/component-lib.vue': {
      routes: '/detail/edit/components/component-lib'
      views: never
    }
    'src/pages/detail/edit/components/component-prop.vue': {
      routes: '/detail/edit/components/component-prop'
      views: never
    }
    'src/pages/detail/edit/components/editor-header.vue': {
      routes: '/detail/edit/components/editor-header'
      views: never
    }
    'src/pages/detail/edit/components/left-panel.vue': {
      routes: '/detail/edit/components/left-panel'
      views: never
    }
    'src/pages/detail/edit/components/right-panel.vue': {
      routes: '/detail/edit/components/right-panel'
      views: never
    }
    'src/pages/detail/stat.vue': {
      routes: '/detail/stat' | '/detail/stat/[:id]'
      views: 'default'
    }
    'src/pages/detail/stat/[:id].vue': {
      routes: '/detail/stat/[:id]'
      views: never
    }
    'src/pages/login.vue': {
      routes: '/login'
      views: never
    }
    'src/pages/manage.vue': {
      routes: '/manage' | '/manage/list' | '/manage/star' | '/manage/trash'
      views: 'default'
    }
    'src/pages/manage/list.vue': {
      routes: '/manage/list'
      views: never
    }
    'src/pages/manage/star.vue': {
      routes: '/manage/star'
      views: never
    }
    'src/pages/manage/trash.vue': {
      routes: '/manage/trash'
      views: never
    }
    'src/pages/register.vue': {
      routes: '/register'
      views: never
    }
  }

  /**
   * Get a union of possible route names in a certain route component file.
   * Used by the volar plugin to automatically type useRoute()
   *
   * @internal
   */
  export type _RouteNamesForFilePath<FilePath extends string> =
    _RouteFileInfoMap extends Record<FilePath, infer Info>
      ? Info['routes']
      : keyof RouteNamedMap
}
